### ISSUE TITLE
Displays in key window, not Flutter window

### ISSUE THREAD

**Issue by stuartmorgan-g** [vanelizarov/flutter_macos_webview#1]
This code:
```
    private lazy var parentViewController: NSViewController = {
        return NSApp.keyWindow!.contentViewController!
    }()
```
is not correct, as there's no guarantee that an application with a Flutter view in it doesn't have other windows. You can get the Flutter view from the plugin registrar's `view` property and work outward from there; there's no need to guess what window the content is in.

**Comment by vanelizarov** [comment]
@stuartmorgan thanks for the remark, fixed in 0.0.3!
