### ISSUE TITLE
Support WebCam

### ISSUE THREAD

**Issue by hpwahyao** [vanelizarov/flutter_macos_webview#10]
Hi @vanelizarov , may I know if can enhance the wedge to support open webcam from the html? e.g. support google meeting. 

Thank you

**Comment by vanelizarov** [comment]
@hpwahyao have you tried to implement it?

Plugin is based on native `WKWebView` which is, roughly speaking, a plain browser with Javascript and all its APIs. Hopefully, there is support for `navigator.mediaDevices.getUserMedia()`

**Comment by hpwahyao** [comment]
sorry for late reply. it does not work.
