### ISSUE TITLE
MissingPluginException(No implementation found for method open on channel com.vanelizarov.flutter_macos_webview/method)

### ISSUE THREAD

**Issue by finnuser** [vanelizarov/flutter_macos_webview#11]
For a more detailed help message, press "h". To quit, press "q".
Error: MissingPluginException(No implementation found for method open on channel com.vanelizarov.flutter_macos_webview/method)
    at Object.throw_ [as throw] (http://localhost:62009/dart_sdk.js:5041:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:62009/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:62009/dart_sdk.js:37403:33

**Comment by vanelizarov** [comment]
@finnuser please provide more detailed description in the future about what you're trying to achieve, in what context your issue appears etc., it's not that hard

As I can see you're trying to use plugin in web app but it's intended to work only on macOS. If you want to implement some auth flow or something like that - prefer to use browser window instead of webview. Also, there are plenty of methods to separate code for web/desktop

**Comment by bchar19087** [comment]
Hi, i got this same message when trying to run the example program  provided with the distribution on the latest version of flutter under macos:

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:50290/TsGBtlKpKAw=/ws
Error: MissingPluginException(No implementation found for method open on channel com.vanelizarov.flutter_macos_webview/method)
    at Object.throw_ [as throw] (http://localhost:50264/dart_sdk.js:5061:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:50264/packages/flutter/src/services/restoration.dart.lib.js:1526:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:50264/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:50264/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50264/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:50264/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:50264/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:50264/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50264/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:50264/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:50264/dart_sdk.js:38784:13)
    at http://localhost:50264/dart_sdk.js:34519:9


flutter --version
Flutter 2.5.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 4cc385b4b8 (5 days ago) • 2021-09-07 23:01:49 -0700
Engine • revision f0826da7ef
Tools • Dart 2.14.0

I'm running a macmini (intel core i5, circa 2018) with MacOS Big Sur 11.5.2, 16Gb memory.

**Comment by vanelizarov** [comment]
@bchar19087 can you please provide minimal runnable example? This issue is not reproducible on my environment:

<details>
<summary>flutter doctor -v</summary>
<pre>
<code>
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/vanelizarov/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (13 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vanelizarov/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/vanelizarov/Library/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.54

• No issues found!
</code>
</pre>
</details>

**Comment by ShiinaOrez** [comment]
I have the same question... When I use webView.open method, it will async invoke channel named  `com.vanelizarov.flutter_macos_webview/method` with method named `open` and some args. 
But I cannot find any implementation of `open` handler. The `_onMethodCall` not handle `open` event.

https://github.com/vanelizarov/flutter_macos_webview/blob/4a1e0aa33ca5ae3c1fffd69fe09ca173d076e155/lib/flutter_macos_webview.dart#L78

Anyone can tell me where is `open` implementation.

**Comment by ShiinaOrez** [comment]
Or anyway, anyone can tell me if I want to implement `open` by myself, what should be returned in the handle function?

**Comment by vanelizarov** [comment]
@ShiinaOrez `open` is implemented [here](https://github.com/vanelizarov/flutter_macos_webview/blob/4a1e0aa33ca5ae3c1fffd69fe09ca173d076e155/macos/Classes/FlutterMacOSWebViewPlugin.swift#L32)
