### ISSUE TITLE
click event 

### ISSUE THREAD

**Issue by lq7y7-go** [vanelizarov/flutter_macos_webview#13]
i can't click flutter project item when i open wkwebview for url.

**Comment by vanelizarov** [comment]
@lq7y7-go please provide minimal runnable example or screenshot/video of what do you mean.

**Comment by esDotDev** [comment]
I'm having problems with being unable to click the "play" button.

Can you open this and play it? `https://www.youtube.com/embed/QZQSISm_QeU`?
