### ISSUE TITLE
flutter: Error: 2, WebResourceErrorType.webContentProcessTerminated, WKErrorDomain, Error Domain=WKErrorDomain Code=2 "(null)"

### ISSUE THREAD

**Issue by zhonghanwen** [vanelizarov/flutter_macos_webview#2]
flutter: Error: 2, WebResourceErrorType.webContentProcessTerminated, WKErrorDomain, Error Domain=WKErrorDomain Code=2 "(null)"

**Comment by vanelizarov** [comment]
@zhonghanwen explain in more detail, please, what do you want 🙂

LMGTFY, the error description speaks for itself, you can read about it in [Apple Docs](https://developer.apple.com/documentation/webkit/wkerror/code):

> An error that indicates the web process that contains the content is no longer running.

**Comment by hpwahyao** [comment]
hi @vanelizarov , could you add the support for the webcam? for example, face-js.

**Comment by nileshtrivedi** [comment]
I ran into the same error:

```
flutter: Opened
flutter: Error: 2, WebResourceErrorType.webContentProcessTerminated, WKErrorDomain, Error Domain=WKErrorDomain Code=2 "(null)"
flutter: Closed
```

My project repo is [available here](https://github.com/nileshtrivedi/devtoolbox/tree/webview_experiment) in the `webview_experiment` branch.

But at the same time, I verified that the example app given here was working correctly with my own set up.

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/helix/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/helix/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

One potential issue could be the fact that I had to manually update to `MACOSX_DEPLOYMENT_TARGET = 10.15` instead of 10.11 inside `macos/` folder to get it to compile in the first place.

**Comment by unhoo28** [comment]
> I ran into the same error:
> 
> ```
> flutter: Opened
> flutter: Error: 2, WebResourceErrorType.webContentProcessTerminated, WKErrorDomain, Error Domain=WKErrorDomain Code=2 "(null)"
> flutter: Closed
> ```
> 
> My project repo is [available here](https://github.com/nileshtrivedi/devtoolbox/tree/webview_experiment) in the `webview_experiment` branch.
> 
> But at the same time, I verified that the example app given here was working correctly with my own set up.
> 
> ```
> $ flutter doctor -v
> [✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
>     • Flutter version 2.8.1 at /Users/helix/Downloads/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
>     • Engine revision 890a5fca2e
>     • Dart version 2.15.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
>     • Android SDK at /Users/helix/Library/Android/sdk
>     • Platform android-32, build-tools 32.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.63.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.32.0
> 
> [✓] Connected device (2 available)
>     • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
>     • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110
> 
> • No issues found!
> ```
> 
> One potential issue could be the fact that I had to manually update to `MACOSX_DEPLOYMENT_TARGET = 10.15` instead of 10.11 inside `macos/` folder to get it to compile in the first place.

you need add the content in macos/Runner/DebugProfile.entitlements
``` xml
<key>com.apple.security.network.client</key>
<true/>
```

**Comment by sr9yar** [comment]
> ```
> <key>com.apple.security.network.client</key>
> <true/>
> ```

...and restart, not hot-reload.
That did it for me, thanks :)

**Comment by nileshtrivedi** [comment]
This works for me too. Thanks :)

Now, I need to figure out how to load a local file in this webview to avoid any data going over the network. Will look up solution for this elsewhere.
