### ISSUE TITLE
引入后启动问题

### ISSUE THREAD

**Issue by 17600777607** [vanelizarov/flutter_macos_webview#4]
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_macos_webview
      - FlutterMacOS

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `flutter_macos_webview` from `Flutter/ephemeral/.symlinks/plugins/flutter_macos_webview/macos`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_macos_webview":
      In Podfile:
        flutter_macos_webview (from `Flutter/ephemeral/.symlinks/plugins/flutter_macos_webview/macos`)

    Specs satisfying the `flutter_macos_webview (from `Flutter/ephemeral/.symlinks/plugins/flutter_macos_webview/macos`)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
    Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1

Exception: Error running pod install

**Comment by vanelizarov** [comment]
@17600777607 have you tried running this command?

> Ignoring ffi-1.13.1 because its extensions are not built. Try: **gem pristine ffi --version 1.13.1**

**Comment by vanelizarov** [comment]
@17600777607 also, please give this issue a name in English

**Comment by joliu1019** [comment]
I got the same error some days ago.
update the code to null safety, then it was work well.

**Comment by weifengsonos** [comment]
> I got the same error some days ago.
> update the code to null safety, then it was work well.

Hi @joliu1019,  I am also getting the same error mentioned above.  How did you update the code to null safety to get around the issue?

**Comment by weifengsonos** [comment]
> > I got the same error some days ago.
> > update the code to null safety, then it was work well.
> 
> Hi @joliu1019, I am also getting the same error mentioned above. How did you update the code to null safety to get around the issue?

I just followed the instructions here ("https://stackoverflow.com/questions/66648374/how-to-migrate-code-to-null-safety-in-dart") and migrated my test code to null safety.  But I am still getting the same issue.  @joliu1019 , could you please explain how you got the "flutter_macos_webview" plugin working on your Mac?

**Comment by weifengsonos** [comment]
Never mind... I figured out how to fix this.  I just need to re-compile Runner.xcodeproj with macOS Deployment Target set to my current Mac OS version (10.15)!

**Comment by vanelizarov** [comment]
@weifengsonos @joliu1019 @17600777607 I've just published new version with null-safety support, please check if it resolves issue

**Comment by weifengsonos** [comment]
@vanelizarov Thanks for the updated version!  The problem that I am seeing now is the issue below, which is one of the closed issues.  I don't know how to fix this.

flutter: Error: 2, WebResourceErrorType.webContentProcessTerminated, WKErrorDomain, Error Domain=WKErrorDomain Code=2 "(null)"

**Comment by vanelizarov** [comment]
@weifengsonos nah, for me it's a random issue, you can simply reload the webview
