### ISSUE TITLE
MacOS OAuth flow

### ISSUE THREAD

**Issue by subhash279** [vanelizarov/flutter_macos_webview#5]
Hi,
Thanks for this plugin.
Can I use this webView to handle google/fb login?
If so how do I get the token back from the webView once customer has successfully entered their credentials?

**Comment by subhash279** [comment]
@vanelizarov pls let me know if you can point me in the right direction to do this. It will be really helpful. 
Thanks :)

**Comment by vanelizarov** [comment]
@subhash279 yeah, it can be used to handle OAuth flow. You can use [`onPageFinished`](https://github.com/vanelizarov/flutter_macos_webview/blob/9ac13d35728a40094363d79e4451a7622550491d/lib/flutter_macos_webview.dart#L25) handler to determine which url is currently loaded and extract auth code from it
