### ISSUE TITLE
Minimum macOS version to 10.14?

### ISSUE THREAD

**Issue by subhash279** [vanelizarov/flutter_macos_webview#6]
Hi,
Is there a reason to set minimum macOS version to 10.14?
I think most apps still run on 10.12.

Thanks!

**Comment by putraxor** [comment]
on Podfile
```
platform :osx, '10.14'
```

**Comment by weifengsonos** [comment]
> on Podfile
> 
> ```
> platform :osx, '10.14'
> ```

Hi @putraxor,

After bumping up the version specified in the Podfile, I am getting the error below.  How did you get around it?

Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
<app_path>/macos/Flutter/GeneratedPluginRegistrant.swift:8:8: error: compiling for macOS 10.11, but module 'flutter_macos_webview' has a minimum deployment target of macOS 10.14: <app_path>/build/macos/Build/Products/Debug/flutter_macos_webview/flutter_macos_webview.framework/Modules/flutter_macos_webview.swiftmodule/x86_64-apple-macos.swiftmodule
import flutter_macos_webview

**Comment by weifengsonos** [comment]
Never mind... I figured out how to fix this.  I just need to re-compile Runner.xcodeproj with macOS Deployment Target set to my current Mac OS version (10.15)!
