### ISSUE TITLE
Platform Exception NO PARENT WINDOW

### ISSUE THREAD

**Issue by giiyms** [vanelizarov/flutter_macos_webview#9]
Hello,

Trying to run the example app and receive this error.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: PlatformException(NO_PARENT_WINDOW, No parent window, null, null)
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:597
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
<asynchronous suspension>
#2      FlutterMacOSWebView.open
package:flutter_macos_webview/flutter_macos_webview.dart:78
<asynchronous suspension>
#3      App._onOpenPressed
package:flutter_macos_webview_example/main.dart:20
<asynchronous suspension>
```

MacOs Version:
• macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
It is a Macbook Air M1 running Big Sur 11.4

Any ideas?

**Comment by tyzam** [comment]
macos/Classes/FlutterMacOSWebViewPlugin.swift
change
  return w.contentViewController?.view == registrar.view
to
  return w.contentViewController?.view == registrar.view?.superview

**Comment by vanelizarov** [comment]
@giiyms can you please include code example? I can't reproduce it on my environment:

<details>
<summary>flutter doctor -v</summary>
<pre>
<code>
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5294g darwin-x64, locale en-US)
• Flutter version 2.2.3 at /Users/vanelizarov/flutter
• Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
• Engine revision 241c87ad80
• Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at /Users/vanelizarov/Library/Android/sdk
• Platform android-30, build-tools 29.0.2
• ANDROID_HOME = /Users/vanelizarov/Library/Android
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.5.1, Build version 12E507
• CocoaPods version 1.10.0

[✓] Chrome - develop for the web
• CHROME_EXECUTABLE = /Users/vanelizarov/Documents/dev/chrome.sh

[✓] Android Studio (version 4.1)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
  🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
  🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.25.0

[✓] Connected device (2 available)
• macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
• Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.131

</code>
</pre>
</details>

**Comment by giiyms** [comment]
> @giiyms can you please include code example? I can't reproduce it on my environment:
> 
> flutter doctor -v

@vanelizarov I was using the example app in the repo. @tyzam's answer fixed it on my machine.

**Comment by giiyms** [comment]
> macos/Classes/FlutterMacOSWebViewPlugin.swift
> change
> return w.contentViewController?.view == registrar.view
> to
> return w.contentViewController?.view == registrar.view?.superview

This is the solution
